# Generated by Django 4.2.7 on 2023-11-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_link_link_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='links',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='string',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
